spring:
  datasource:
    url: jdbc:mysql://localhost:3306/znzy
    #jdbc????? ????jdbc:mysql://????????:??/????
    username: root
    #?????
    password: 19805601056Bkj@@
    #?????
    driver-class-name: com.mysql.cj.jdbc.Driver
    #??????

#???MySQL????????????????????